project:
  type: website

website:
  title: "IS415 Geospatial Analytics and Applications"
  navbar:
    right:
      - text: In-class Exercise
        menu:
          - text: In-class Exercise 2
            href: In-class_Ex/In-class_Ex02/In-class_Ex02.html
          - text: In-class Exercise 3
            href: In-class_Ex/In-class_Ex03/In-class_Ex03.html
          - text: In-class Exercise 3B
            href: In-class_Ex/In-class_Ex03/In-class_Ex03_KDE.html
          - text: In-class Exercise 4
            href: In-class_Ex/In-class_Ex04/In-class_Ex04.html
      - text: Hands-on Exercise
        menu:
          - text: Hands-on Exercise 1
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
          - text: Hands-on Exercise 2
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html
          - text: Hands-on Exercise 3A
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03A.html
          - text: Hands-on Exercise 3B
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03B.html
          - text: Hands-on Exercise 4
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html
      - text: Take-home Exercise
        menu:
          - text: Take-home Exercise 1
            href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

