<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-03-01">

<title>IS415 Geospatial Analytics and Applications - Take-home Exercise 2:Application of Spatial and Spatio-temporal Analysis Methods to Discover the Distribution of Dengue Fever in Tainan City, Taiwan</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="../../site_libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="../../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../../site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../../site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415 Geospatial Analytics and Applications</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03_KDE.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 3B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex05.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03A.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 3A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03B.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 3B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05A.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 5A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05B.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 5B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1.0 Introduction</a>
  <ul class="collapse">
  <li><a href="#overview---setting-the-scene" id="toc-overview---setting-the-scene" class="nav-link" data-scroll-target="#overview---setting-the-scene">1.1. Overview - Setting the Scene</a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">1.2 Objectives</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">1.3 Getting Started</a></li>
  </ul></li>
  <li><a href="#data-acquisition" id="toc-data-acquisition" class="nav-link" data-scroll-target="#data-acquisition">2.0 Data Acquisition</a></li>
  <li><a href="#importing-geospatial-and-aspatial-data" id="toc-importing-geospatial-and-aspatial-data" class="nav-link" data-scroll-target="#importing-geospatial-and-aspatial-data">3.0 Importing Geospatial and Aspatial Data</a>
  <ul class="collapse">
  <li><a href="#importing-geospatial-data" id="toc-importing-geospatial-data" class="nav-link" data-scroll-target="#importing-geospatial-data">3.1 Importing Geospatial data</a></li>
  <li><a href="#importing-aspatial-data" id="toc-importing-aspatial-data" class="nav-link" data-scroll-target="#importing-aspatial-data">3.2 Importing Aspatial data</a></li>
  </ul></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">4.0 Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#preparing-a-study-area-layer-with-specific-towns-of-tainan-city-taiwan" id="toc-preparing-a-study-area-layer-with-specific-towns-of-tainan-city-taiwan" class="nav-link" data-scroll-target="#preparing-a-study-area-layer-with-specific-towns-of-tainan-city-taiwan">4.1 Preparing a study area layer with specific towns of Tainan City, Taiwan</a></li>
  <li><a href="#preparing-a-dengue-fever-layer-with-specific-towns-of-tainan-city-taiwan" id="toc-preparing-a-dengue-fever-layer-with-specific-towns-of-tainan-city-taiwan" class="nav-link" data-scroll-target="#preparing-a-dengue-fever-layer-with-specific-towns-of-tainan-city-taiwan">4.2 Preparing a dengue fever layer with specific towns of Tainan City, Taiwan</a>
  <ul class="collapse">
  <li><a href="#confining-dengue-fever-layer-with-townids-d01-d02-d04-d06-d07-d08-d32-and-d39" id="toc-confining-dengue-fever-layer-with-townids-d01-d02-d04-d06-d07-d08-d32-and-d39" class="nav-link" data-scroll-target="#confining-dengue-fever-layer-with-townids-d01-d02-d04-d06-d07-d08-d32-and-d39">4.2.1 Confining dengue fever layer with TOWNIDs D01, D02, D04, D06, D07, D08, D32 and D39</a></li>
  <li><a href="#extracting-dengue-fever-cases-within-epidemiology-week-31-50-2023" id="toc-extracting-dengue-fever-cases-within-epidemiology-week-31-50-2023" class="nav-link" data-scroll-target="#extracting-dengue-fever-cases-within-epidemiology-week-31-50-2023">4.2.2 Extracting dengue fever cases within epidemiology week 31-50, 2023</a></li>
  </ul></li>
  <li><a href="#preparing-a-dengue-fever-layer-in-spacetime-d3-class-of-sfdep" id="toc-preparing-a-dengue-fever-layer-in-spacetime-d3-class-of-sfdep" class="nav-link" data-scroll-target="#preparing-a-dengue-fever-layer-in-spacetime-d3-class-of-sfdep">4.3 Preparing a dengue fever layer in spacetime d3 class of sfdep</a></li>
  <li><a href="#preparing-for-exploratory-data-analysis" id="toc-preparing-for-exploratory-data-analysis" class="nav-link" data-scroll-target="#preparing-for-exploratory-data-analysis">4.4 Preparing for Exploratory Data Analysis</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">5.0 Exploratory Data Analysis</a></li>
  <li><a href="#spatial-autocorrelation-analysis" id="toc-spatial-autocorrelation-analysis" class="nav-link" data-scroll-target="#spatial-autocorrelation-analysis">6.0 Spatial Autocorrelation Analysis</a>
  <ul class="collapse">
  <li><a href="#global-spatial-autocorrelation-analysis" id="toc-global-spatial-autocorrelation-analysis" class="nav-link" data-scroll-target="#global-spatial-autocorrelation-analysis">6.2.1 Global Spatial Autocorrelation Analysis</a></li>
  <li><a href="#local-spatial-autocorrelation-analysis" id="toc-local-spatial-autocorrelation-analysis" class="nav-link" data-scroll-target="#local-spatial-autocorrelation-analysis">6.2.2 Local Spatial Autocorrelation Analysis</a></li>
  <li><a href="#hot-spot-and-cold-spot-area-analysis-hcsa" id="toc-hot-spot-and-cold-spot-area-analysis-hcsa" class="nav-link" data-scroll-target="#hot-spot-and-cold-spot-area-analysis-hcsa">6.2.3 Hot Spot and Cold Spot Area Analysis (HCSA)</a></li>
  </ul></li>
  <li><a href="#emerging-hot-spot-analysis-ehsa" id="toc-emerging-hot-spot-analysis-ehsa" class="nav-link" data-scroll-target="#emerging-hot-spot-analysis-ehsa">7.0 Emerging Hot Spot Analysis (EHSA)</a>
  <ul class="collapse">
  <li><a href="#derive-spatial-weights-1" id="toc-derive-spatial-weights-1" class="nav-link" data-scroll-target="#derive-spatial-weights-1">7.1 Derive Spatial Weights</a></li>
  <li><a href="#compute-gi-statistics-1" id="toc-compute-gi-statistics-1" class="nav-link" data-scroll-target="#compute-gi-statistics-1">7.2 Compute Gi* statistics</a></li>
  <li><a href="#mann-kendall-test" id="toc-mann-kendall-test" class="nav-link" data-scroll-target="#mann-kendall-test">7.3 Mann-Kendall Test</a></li>
  <li><a href="#performing-emerging-hotspot-analysis" id="toc-performing-emerging-hotspot-analysis" class="nav-link" data-scroll-target="#performing-emerging-hotspot-analysis">7.4 Performing Emerging Hotspot Analysis</a>
  <ul class="collapse">
  <li><a href="#visualising-the-distribution-of-ehsa-classes" id="toc-visualising-the-distribution-of-ehsa-classes" class="nav-link" data-scroll-target="#visualising-the-distribution-of-ehsa-classes">7.4.1 Visualising the distribution of EHSA classes</a></li>
  <li><a href="#visualising-ehsa" id="toc-visualising-ehsa" class="nav-link" data-scroll-target="#visualising-ehsa">7.4.2 Visualising EHSA</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">8.0 References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 2:Application of Spatial and Spatio-temporal Analysis Methods to Discover the Distribution of Dengue Fever in Tainan City, Taiwan</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 1, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>1.0 Introduction</h1>
<section id="overview---setting-the-scene" class="level2">
<h2 class="anchored" data-anchor-id="overview---setting-the-scene">1.1. Overview - Setting the Scene</h2>
<p><a href="https://www.cdc.gov/dengue/resources/denguedhf-information-for-health-care-practitioners_2009.pdf">Dengue Hemorrhagic Fever</a> (in short dengue fever) is one of the most widespread mosquito-borne diseases in the most tropical and subtropical regions. It is an acute disease caused by dengue virus infection which is transmitted by female Aedes aegypti and Aedes albopictus mosquitoes.</p>
<p>In 2015, Taiwan had recorded the most severe dengue fever outbreak with <strong>more than 43,000 dengue cases</strong> and <strong>228 deaths</strong>. Since then, the annual reported dengue fever cases were maintained at the level of not more than 200 cases. However, in <strong>2023</strong>, Taiwan recorded <strong>26703 dengue fever cases</strong>.</p>
</section>
<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">1.2 Objectives</h2>
<p>In this study, we are interested to discover:</p>
<ul>
<li><p>If the distribution of dengue fever outbreak at Tainan City, Taiwan are independent from spatial (space) and spatio-temporal (space-time).</p></li>
<li><p>If the outbreak is indeed spatial and spatio-temporal dependent, then, you would like to detect where are the clusters and outliers, and the emerging hot spot/cold spot areas.</p></li>
</ul>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">1.3 Getting Started</h2>
<p>In this take-home exercise, we will be using the following packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(Kendall, plotly, tidyverse, tmap, sf, sp, sfdep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="data-acquisition" class="level1">
<h1>2.0 Data Acquisition</h1>
<p>We will be using <strong>2 data sets</strong> in this exercise:</p>
<table class="table">
<thead>
<tr class="header">
<th>Data</th>
<th>Format</th>
<th>Description</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TAIWAN_VILLAGE_2020</td>
<td>ESRI Shapefile</td>
<td>A geospatial data of village boundary of Taiwan</td>
<td><a href="https://data.gov.tw/en/datasets/130549">data.gov.tw</a></td>
</tr>
<tr class="even">
<td>Dengue_Daily.csv</td>
<td>csv</td>
<td>An aspatial data of reported dengue cases in Taiwan since 1998</td>
<td><a href="https://data.cdc.gov.tw/en/dataset/dengue-daily-determined-cases-1998">Taiwan CDC Open Data Portal</a></td>
</tr>
</tbody>
</table>
<p>Create a new folder labelled <code>Take-home_Ex02</code> and place all the files into this folder.</p>
</section>
<section id="importing-geospatial-and-aspatial-data" class="level1">
<h1>3.0 Importing Geospatial and Aspatial Data</h1>
<section id="importing-geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-geospatial-data">3.1 Importing Geospatial data</h2>
<p><strong>TAIWAN_VILLAGE_2020</strong></p>
<p>The TAIWAN_VILLAGE_2020 dataset was acquired in ESRI shapefile format (.shp). To utilise this dataset in the R-environment, we need to import it as an sf object using the st_read() function from the sf package. This function is used to read the shapefile containing the administrative boundaries of Tainan City and returns an sf object named <code>tainan_sf</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>tainan_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>, </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">layer =</span> <span class="st">"TAINAN_VILLAGE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `TAINAN_VILLAGE' from data source 
  `C:\kt526\IS415-GAA\Take-home_Ex\Take-home_Ex02\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 649 features and 10 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 120.0269 ymin: 22.88751 xmax: 120.6563 ymax: 23.41374
Geodetic CRS:  TWD97</code></pre>
</div>
</div>
<p>The dataset “TAINAN_VILLAGE” represents the polygon features delineating village boundaries within the Tainan City region of Taiwan. It comprises 649 features, each feature corresponding to a distinct village area. The dataset includes 10 fields providing additional attributes associated with each village polygon.</p>
</section>
<section id="importing-aspatial-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-aspatial-data">3.2 Importing Aspatial data</h2>
<p><strong>Dengue_Daily</strong></p>
<p>The Dengue_Daily dataset is available in csv format (.csv) and was obtained from the Taiwan CDC Open Data Portal. Like the previous dataset, it needs to be imported into the R environment for use. However, since this dataset is aspatial and in csv format, a different method is required for reading it. We will utilize the read_csv() function to import the csv dataset and store the object in a tibble data frame named <code>dengue</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dengue <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/Dengue_Daily.csv"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dengue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 26
  發病日     個案研判日 通報日     性別  年齡層 居住縣市 居住鄉鎮 居住村里
  &lt;date&gt;     &lt;chr&gt;      &lt;date&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;   
1 1998-01-02 None       1998-01-07 男    40-44  屏東縣   屏東市   None    
2 1998-01-03 None       1998-01-14 男    30-34  屏東縣   東港鎮   None    
3 1998-01-13 None       1998-02-18 男    55-59  宜蘭縣   宜蘭市   None    
4 1998-01-15 None       1998-01-23 男    35-39  高雄市   苓雅區   None    
5 1998-01-20 None       1998-02-04 男    55-59  宜蘭縣   五結鄉   None    
6 1998-01-22 None       1998-02-19 男    20-24  桃園市   蘆竹區   None    
# ℹ 18 more variables: 最小統計區 &lt;chr&gt;, 最小統計區中心點X &lt;chr&gt;,
#   最小統計區中心點Y &lt;chr&gt;, 一級統計區 &lt;chr&gt;, 二級統計區 &lt;chr&gt;,
#   感染縣市 &lt;chr&gt;, 感染鄉鎮 &lt;chr&gt;, 感染村里 &lt;chr&gt;, 是否境外移入 &lt;chr&gt;,
#   感染國家 &lt;chr&gt;, 確定病例數 &lt;dbl&gt;, 居住村里代碼 &lt;chr&gt;, 感染村里代碼 &lt;chr&gt;,
#   血清型 &lt;chr&gt;, 內政部居住縣市代碼 &lt;chr&gt;, 內政部居住鄉鎮代碼 &lt;chr&gt;,
#   內政部感染縣市代碼 &lt;chr&gt;, 內政部感染鄉鎮代碼 &lt;chr&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="data-wrangling" class="level1">
<h1>4.0 Data Wrangling</h1>
<section id="preparing-a-study-area-layer-with-specific-towns-of-tainan-city-taiwan" class="level2">
<h2 class="anchored" data-anchor-id="preparing-a-study-area-layer-with-specific-towns-of-tainan-city-taiwan">4.1 Preparing a study area layer with specific towns of Tainan City, Taiwan</h2>
<p>In this Take-home Exercise, we are interested in narrowing our focus to specific towns within Tainan City, specifically <strong>D01, D02, D04, D06, D07, D08, D32, and D39</strong>. To prepare a study area layer focusing on these specific towns, we can do the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>towns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'D01'</span>, <span class="st">'D02'</span>, <span class="st">'D04'</span>, <span class="st">'D06'</span>, <span class="st">'D07'</span>, <span class="st">'D08'</span>, <span class="st">'D32'</span>, <span class="st">'D39'</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>tainan_towns_sf <span class="ot">&lt;-</span> tainan_sf <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(COUNTYNAME,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>         TOWNID,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>         TOWNNAME,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>         VILLNAME,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>         geometry) <span class="sc">%&gt;%</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TOWNNAME_VILLNAME =</span> <span class="fu">paste</span>(TOWNNAME, VILLNAME, <span class="at">sep=</span><span class="st">"_"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TOWNID <span class="sc">%in%</span> towns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>filtered_rows <span class="ot">&lt;-</span> tainan_sf[tainan_sf<span class="sc">$</span>TOWNID <span class="sc">%in%</span> towns, ]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>unique_townnames <span class="ot">&lt;-</span> <span class="fu">unique</span>(filtered_rows<span class="sc">$</span>TOWNNAME)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(unique_townnames)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "安南區" "仁德區" "中西區" "南區"   "永康區" "東區"   "北區"   "安平區"</code></pre>
</div>
</div>
<p>The c() function is used to combine the specified towns into a vector (a one dimensional array) named <code>towns</code>. Next, we will filter the Tainan City spatial data frame (<code>tainan_sf</code>) based on the <code>TOWNID</code> column, selecting only those entries that match the towns of interest listed in the <code>towns</code> vector. This refined dataset, named <code>tainan_towns_sf</code>, will serve as our study area layer for further analysis or visualization tasks.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>To ensure that the filter() function works properly, we can check the unique values present in the <code>TOWNID</code> field using the unique() function.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(tainan_towns_sf<span class="sc">$</span>TOWNID)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "D06" "D32" "D08" "D02" "D39" "D01" "D04" "D07"</code></pre>
</div>
</div>
<p>And here’s how our map for the study area looks like:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="preparing-a-dengue-fever-layer-with-specific-towns-of-tainan-city-taiwan" class="level2">
<h2 class="anchored" data-anchor-id="preparing-a-dengue-fever-layer-with-specific-towns-of-tainan-city-taiwan">4.2 Preparing a dengue fever layer with specific towns of Tainan City, Taiwan</h2>
<p>The subsequent tasks entail preparing the dengue fever layer for specific towns within Tainan City, Taiwan. This involves:</p>
<ol type="1">
<li>Confining dengue fever layer with TOWNIDs D01, D02, D04, D06, D07, D08, D32 and D39</li>
<li>Extracting dengue fever cases within epidemiology week 31-50, 2023</li>
</ol>
<p>Firstly, we use the colnames() function to see all the column names present in <code>dengue</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(dengue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "發病日"             "個案研判日"         "通報日"            
 [4] "性別"               "年齡層"             "居住縣市"          
 [7] "居住鄉鎮"           "居住村里"           "最小統計區"        
[10] "最小統計區中心點X"  "最小統計區中心點Y"  "一級統計區"        
[13] "二級統計區"         "感染縣市"           "感染鄉鎮"          
[16] "感染村里"           "是否境外移入"       "感染國家"          
[19] "確定病例數"         "居住村里代碼"       "感染村里代碼"      
[22] "血清型"             "內政部居住縣市代碼" "內政部居住鄉鎮代碼"
[25] "內政部感染縣市代碼" "內政部感染鄉鎮代碼"</code></pre>
</div>
</div>
<p>After reading in the dengue dataset, we will notice that the dataset contains 26 variables (columns). Similar to <code>tainan_sf</code>, not all columns will be relevant for our investigation. So, let us select the relevant columns from <code>dengue</code> and rename them so that its easier for our analysis later on.</p>
<ul>
<li><p><strong>發病日:</strong> ONSET_DATE</p></li>
<li><p><strong>最小統計區中心點X:</strong> X_COORDINATE (longitude)</p></li>
<li><p><strong>最小統計區中心點Y:</strong> Y_COORDINATE (latitude)</p></li>
<li><p><strong>居住縣市:</strong> COUNTYNAME</p></li>
<li><p><strong>居住鄉鎮:</strong> TOWNNAME</p></li>
<li><p><strong>居住村里:</strong> VILLNAME</p></li>
</ul>
<p>Let us save the output as a variable called <code>dengue_extracted</code>. Afterwards, we will display the structure of <code>dengue_extracted</code> using str().</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>dengue_extracted <span class="ot">&lt;-</span> dengue <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(發病日,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>         最小統計區中心點X,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>         最小統計區中心點Y,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>         居住縣市,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>         居住鄉鎮,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>         居住村里) <span class="sc">%&gt;%</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"ONSET_DATE"</span> <span class="ot">=</span> 發病日,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>         <span class="st">"X_COORDINATE"</span> <span class="ot">=</span> 最小統計區中心點X,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Y_COORDINATE"</span> <span class="ot">=</span> 最小統計區中心點Y,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>         <span class="st">"COUNTYNAME"</span> <span class="ot">=</span> 居住縣市,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>         <span class="st">"TOWNNAME"</span> <span class="ot">=</span> 居住鄉鎮,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>         <span class="st">"VILLNAME"</span> <span class="ot">=</span> 居住村里)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dengue_extracted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [106,861 × 6] (S3: tbl_df/tbl/data.frame)
 $ ONSET_DATE  : Date[1:106861], format: "1998-01-02" "1998-01-03" ...
 $ X_COORDINATE: chr [1:106861] "120.505898941" "120.453657460" "121.751433765" "120.338158907" ...
 $ Y_COORDINATE: chr [1:106861] "22.464206650" "22.466338948" "24.749214667" "22.630316700" ...
 $ COUNTYNAME  : chr [1:106861] "屏東縣" "屏東縣" "宜蘭縣" "高雄市" ...
 $ TOWNNAME    : chr [1:106861] "屏東市" "東港鎮" "宜蘭市" "苓雅區" ...
 $ VILLNAME    : chr [1:106861] "None" "None" "None" "None" ...</code></pre>
</div>
</div>
<p>The <code>dengue_extracted</code> is a tibble data.frame and we are now left with 6 variables.</p>
<p>We can also use RStudio’s <a href="https://docs.posit.co/ide/user/ide/guide/data/data-viewer.html">Data Viewer</a> to view the contents of <code>dengue_extracted</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="imgs/dengue_extracted_view.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>Notice the following after using the str() and viewing the <code>dengue_extracted</code> contents from Data Viewer :</p>
<ul>
<li><p><code>X_COORDINATE</code> and <code>Y_COORDINATE</code> are in chr and contains “None”</p></li>
<li><p><code>VILLNAME</code> contains “None”</p></li>
<li><p><code>ONSET_DATE</code> includes year such as 1998 (We only want year 2023)</p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The str() function is articularly useful for getting a quick summary of the structure of the data, including the data types of each column and a glimpse of the actual data.</p>
</div>
</div>
<p>We definitely have to do something about this … Let us fix these issues and also create a new column called <code>EPIWEEK</code> using the code chunk below. The output will be saved in <code>dengue_2023</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>dengue_2023 <span class="ot">&lt;-</span> dengue_extracted <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">year</span>(ONSET_DATE) <span class="sc">==</span> <span class="dv">2023</span> <span class="sc">&amp;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>           X_COORDINATE <span class="sc">!=</span> <span class="st">"None"</span> <span class="sc">&amp;</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>           Y_COORDINATE <span class="sc">!=</span> <span class="st">"None"</span> <span class="sc">&amp;</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>           VILLNAME <span class="sc">!=</span> <span class="st">"None"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">X_COORDINATE =</span> <span class="fu">as.numeric</span>(X_COORDINATE),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">Y_COORDINATE =</span> <span class="fu">as.numeric</span>(Y_COORDINATE),</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">EPIWEEK =</span> <span class="fu">epiweek</span>(ONSET_DATE))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dengue_2023)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [24,047 × 7] (S3: tbl_df/tbl/data.frame)
 $ ONSET_DATE  : Date[1:24047], format: "2023-01-01" "2023-01-03" ...
 $ X_COORDINATE: num [1:24047] 120 120 120 120 121 ...
 $ Y_COORDINATE: num [1:24047] 22.8 22.8 22.7 23 24.2 ...
 $ COUNTYNAME  : chr [1:24047] "高雄市" "屏東縣" "高雄市" "台南市" ...
 $ TOWNNAME    : chr [1:24047] "岡山區" "里港鄉" "仁武區" "東區" ...
 $ VILLNAME    : chr [1:24047] "灣裡里" "三廍村" "文武里" "崇文里" ...
 $ EPIWEEK     : num [1:24047] 1 1 2 5 5 5 5 7 9 12 ...</code></pre>
</div>
</div>
<p>After running the code chunk above, we will see that the new column <code>EPIWEEK</code> has been added into <code>dengue_2023</code>. <code>X_COORDINATE</code> and <code>Y_COORDINATE</code> are also now having <code>num</code> data type.</p>
<p>To check if the “None” values are still present in <code>X_COORDINATE</code>, <code>Y_COORDINATE</code> and <code>VILLNAME</code>, we can run the following code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>dengue_2023 <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"None"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24,047 × 0</code></pre>
</div>
</div>
<p>If we were to look at <code>dengue_2023</code> from the Data Viewer, we can observe that the <code>COUNTYNAME</code> contains counties besides 台南市, <code>TOWNNAME</code> contains more than the 8 unique towns we want and EPIWEEK is not within 31 to 50.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="imgs/dengue_2023.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>We can verify this by using the unique() function.</p>
<p>Unique County names (<code>COUNTYNAME</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dengue_2023<span class="sc">$</span>COUNTYNAME)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "高雄市" "屏東縣" "台南市" "台中市" "台東縣" "台北市" "花蓮縣" "雲林縣"
 [9] "桃園市" "南投縣" "彰化縣" "新北市" "新竹市" "宜蘭縣" "新竹縣" "苗栗縣"
[17] "嘉義縣" "基隆市" "嘉義市" "澎湖縣" "金門縣"</code></pre>
</div>
</div>
<p>Unique Town names (<code>TOWNNAME</code>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dengue_2023<span class="sc">$</span>TOWNNAME)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "岡山區"   "里港鄉"   "仁武區"   "東區"     "北區"     "鳥松區"  
  [7] "歸仁區"   "鼓山區"   "善化區"   "楠梓區"   "新化區"   "大里區"  
 [13] "鳳山區"   "北屯區"   "大甲區"   "西屯區"   "永康區"   "烏日區"  
 [19] "台東市"   "萬華區"   "壽豐鄉"   "中區"     "仁德區"   "古坑鄉"  
 [25] "南屯區"   "后里區"   "龍潭區"   "太平區"   "南投市"   "安南區"  
 [31] "茄萣區"   "南區"     "斗六市"   "中壢區"   "沙鹿區"   "屏東市"  
 [37] "台西鄉"   "湖內區"   "芳苑鄉"   "板橋區"   "三民區"   "太麻里鄉"
 [43] "新營區"   "左營區"   "大寮區"   "路竹區"   "大社區"   "永和區"  
 [49] "三重區"   "中西區"   "淡水區"   "新市區"   "阿蓮區"   "中山區"  
 [55] "深坑區"   "壯圍鄉"   "新埔鎮"   "關廟區"   "虎尾鎮"   "信義區"  
 [61] "西區"     "苓雅區"   "林內鄉"   "前鎮區"   "梓官區"   "北投區"  
 [67] "竹山鎮"   "柳營區"   "松山區"   "樹林區"   "八德區"   "前金區"  
 [73] "旗津區"   "萬丹鄉"   "左鎮區"   "小港區"   "楠西區"   "七股區"  
 [79] "大同區"   "頭份市"   "汐止區"   "大林鎮"   "竹崎鄉"   "莿桐鄉"  
 [85] "安平區"   "平鎮區"   "清水區"   "梅山鄉"   "彰化市"   "豐原區"  
 [91] "中正區"   "潮州鎮"   "湖口鄉"   "桃園區"   "竹田鄉"   "西港區"  
 [97] "花蓮市"   "士林區"   "安樂區"   "文山區"   "佳里區"   "大安區"  
[103] "大雅區"   "南化區"   "楊梅區"   "彌陀區"   "八里區"   "麻豆區"  
[109] "溪州鄉"   "斗南鎮"   "新莊區"   "大村鄉"   "玉井區"   "竹北市"  
[115] "新店區"   "外埔區"   "蘆洲區"   "竹東鎮"   "林園區"   "大埤鄉"  
[121] "六甲區"   "安定區"   "西螺鎮"   "蘆竹區"   "太保市"   "香山區"  
[127] "橋頭區"   "二林鎮"   "官田區"   "通霄鎮"   "九如鄉"   "大樹區"  
[133] "旗山區"   "學甲區"   "大溪區"   "七堵區"   "中和區"   "大內區"  
[139] "龍崎區"   "內門區"   "民雄鄉"   "新興區"   "鹽埕區"   "桃源區"  
[145] "大肚區"   "南港區"   "名間鄉"   "田寮區"   "長治鄉"   "鹿港鎮"  
[151] "山上區"   "神岡區"   "泰山區"   "下營區"   "埔里鎮"   "水上鄉"  
[157] "佳冬鄉"   "燕巢區"   "鹽水區"   "中埔鄉"   "杉林區"   "五股區"  
[163] "布袋鎮"   "朴子市"   "新園鄉"   "三峽區"   "來義鄉"   "內湖區"  
[169] "麥寮鄉"   "麟洛鄉"   "礁溪鄉"   "林口區"   "番路鄉"   "將軍區"  
[175] "內埔鄉"   "龜山區"   "二崙鄉"   "和美鎮"   "甲仙區"   "公館鄉"  
[181] "東港鎮"   "美濃區"   "仁愛鄉"   "宜蘭市"   "龍井區"   "觀音區"  
[187] "恆春鎮"   "頭城鎮"   "後壁區"   "土城區"   "綠島鄉"   "高樹鄉"  
[193] "新豐鄉"   "春日鄉"   "萬巒鄉"   "埤頭鄉"   "員林市"   "馬公市"  
[199] "溪湖鎮"   "新港鄉"   "鹽埔鄉"   "三星鄉"   "林邊鄉"   "五結鄉"  
[205] "潭子區"   "北斗鎮"   "新埤鄉"   "霧峰區"   "集集鎮"   "東山區"  
[211] "湖西鄉"   "蘇澳鎮"   "瑪家鄉"   "土庫鎮"   "崁頂鄉"   "牡丹鄉"  
[217] "崙背鄉"   "成功鎮"   "六龜區"   "金城鎮"   "伸港鄉"   "花壇鄉"  
[223] "四湖鄉"   "竹南鎮"   "鹿谷鄉"  </code></pre>
</div>
</div>
<p>Unique Epiweek (<code>EPIWEEK</code>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dengue_2023<span class="sc">$</span>EPIWEEK)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1  2  5  7  9 12 13 14 15 16 17 19 20 22 23 24 25 26 27 28 29 30 31 32 33
[26] 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52</code></pre>
</div>
</div>
<section id="confining-dengue-fever-layer-with-townids-d01-d02-d04-d06-d07-d08-d32-and-d39" class="level3">
<h3 class="anchored" data-anchor-id="confining-dengue-fever-layer-with-townids-d01-d02-d04-d06-d07-d08-d32-and-d39">4.2.1 Confining dengue fever layer with TOWNIDs D01, D02, D04, D06, D07, D08, D32 and D39</h3>
<p>We need to filter <code>COUNTYNAME</code> to contain only 台南市 and <code>TOWNNAME</code> to contain only the 8 specific towns (安南區, 仁德區, 中西區, 南區, 永康區, 東區, 北區, 安平區). We will save the output in <code>dengue_fever_layer_df</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>dengue_fever_layer_df <span class="ot">&lt;-</span> dengue_2023 <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TOWNNAME_VILLNAME =</span> <span class="fu">paste</span>(TOWNNAME, VILLNAME, <span class="at">sep=</span><span class="st">"_"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(COUNTYNAME <span class="sc">==</span> <span class="st">"台南市"</span> <span class="sc">&amp;</span> TOWNNAME <span class="sc">%in%</span> unique_townnames)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let us check <code>COUNTYNAME</code> and <code>TOWNNAME</code> in <code>dengue_fever_layer_df</code>. We should observe that we only have 1 specific county and 8 towns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"County:"</span>, <span class="fu">unique</span>(dengue_fever_layer_df<span class="sc">$</span>COUNTYNAME))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>County: 台南市</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Towns:"</span>, <span class="fu">unique</span>(dengue_fever_layer_df<span class="sc">$</span>TOWNNAME))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Towns: 東區 永康區 仁德區 北區 安南區 南區 中西區 安平區</code></pre>
</div>
</div>
</section>
<section id="extracting-dengue-fever-cases-within-epidemiology-week-31-50-2023" class="level3">
<h3 class="anchored" data-anchor-id="extracting-dengue-fever-cases-within-epidemiology-week-31-50-2023">4.2.2 Extracting dengue fever cases within epidemiology week 31-50, 2023</h3>
<p>Let us visualize the distribution of dengue fever cases across the epidemiology weeks in 2023.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dengue_fever_layer_df, <span class="fu">aes</span>(<span class="at">x =</span> EPIWEEK)) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"grey"</span>) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"EPIWEEK"</span>, <span class="at">y =</span> <span class="st">"Number of dengue cases"</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Distribution of Dengue Cases in 2023 by Epidemiology weeks"</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>More than 80%</strong> of the reported dengue fever cases occurred in <strong>epidemiology week 31-50, 2023</strong>. Let us filter out these dengue fever cases that falls within epidemiology week 31 to 50.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>dengue_2023_epiweeks_31_50_df <span class="ot">&lt;-</span> dengue_fever_layer_df <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">between</span>(EPIWEEK, <span class="dv">31</span>, <span class="dv">50</span>) )</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dengue_2023_epiweeks_31_50_df<span class="sc">$</span>EPIWEEK)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50</code></pre>
</div>
</div>
</section>
</section>
<section id="preparing-a-dengue-fever-layer-in-spacetime-d3-class-of-sfdep" class="level2">
<h2 class="anchored" data-anchor-id="preparing-a-dengue-fever-layer-in-spacetime-d3-class-of-sfdep">4.3 Preparing a dengue fever layer in spacetime d3 class of sfdep</h2>
<p>The next task is to prepare dengue fever layer in spacetime d3 class using the sfdep package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>dengue_grp <span class="ot">&lt;-</span> dengue_2023_epiweeks_31_50_df <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TOWNNAME_VILLNAME, EPIWEEK) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">num_dengue_cases =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">complete</span>(<span class="at">EPIWEEK =</span> <span class="dv">31</span><span class="sc">:</span><span class="dv">50</span>, <span class="at">fill =</span> <span class="fu">list</span>(<span class="at">num_dengue_cases =</span> <span class="dv">0</span>))</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>dengue_grp <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(dengue_grp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>tainan_towns_with_dengue <span class="ot">&lt;-</span> tainan_towns_sf <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TOWNNAME_VILLNAME =</span> <span class="fu">paste</span>(TOWNNAME, VILLNAME, <span class="at">sep=</span><span class="st">"_"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(TOWNNAME_VILLNAME, geometry) <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TOWNNAME_VILLNAME <span class="sc">%in%</span> <span class="fu">unique</span>(dengue_grp<span class="sc">$</span>TOWNNAME_VILLNAME))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>tainan_dengue_st <span class="ot">&lt;-</span> <span class="fu">spacetime</span>(<span class="at">.data =</span> dengue_grp,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">.geometry =</span> tainan_towns_with_dengue,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">.loc_col =</span> <span class="st">"TOWNNAME_VILLNAME"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">.time_col =</span> <span class="st">"EPIWEEK"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is_spacetime_cube</span>(tainan_dengue_st)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong><code>TRUE</code></strong> return confirms that <code>tainan_dengue_st</code> is indeed an time-space cube.</p>
</div>
</div>
</section>
<section id="preparing-for-exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="preparing-for-exploratory-data-analysis">4.4 Preparing for Exploratory Data Analysis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>total_dengue_cases_by_village <span class="ot">&lt;-</span> dengue_grp <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(TOWNNAME_VILLNAME,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>         num_dengue_cases) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TOWNNAME_VILLNAME) <span class="sc">%&gt;%</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_dengue_cases =</span> <span class="fu">sum</span>(num_dengue_cases))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>tainan_dengue_cases_by_village <span class="ot">&lt;-</span> <span class="fu">left_join</span>(tainan_towns_sf,</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>                                            total_dengue_cases_by_village,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>                                            <span class="at">by =</span> <span class="st">"TOWNNAME_VILLNAME"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replace_na</span>(<span class="fu">list</span>(<span class="at">total_dengue_cases =</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(tainan_dengue_cases_by_village))<span class="sc">&gt;</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>named integer(0)</code></pre>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis" class="level1">
<h1>5.0 Exploratory Data Analysis</h1>
<p>In this section, we want to visualize the distribution of dengue fever cases across the 8 specific towns (安南區, 仁德區, 中西區, 南區, 永康區, 東區, 北區, 安平區) and within the epidemiology weeks from 31 to 50. By doing so, we can gain insights into the intensity of the disease and discover any patterns.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>tainan_dengue_cases_by_village_map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(tainan_dengue_cases_by_village) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"total_dengue_cases"</span>,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"jenks"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Reds"</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Number of Dengue Cases"</span>,</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">legend.show =</span> <span class="cn">TRUE</span>,</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">popup.vars =</span> <span class="fu">c</span>(<span class="st">"total_dengue_cases"</span>)) <span class="sc">+</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Distribution of Dengue Cases in Tainan Towns"</span>,</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.85</span>,</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.5</span>,</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.4</span>,</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>tainan_towns_map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(tainan_towns_sf) <span class="sc">+</span> </span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"TOWNNAME"</span>) <span class="sc">+</span> </span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Map of Tainan Towns"</span>,</span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.85</span>,</span>
<span id="cb43-26"><a href="#cb43-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb43-27"><a href="#cb43-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.4</span>,</span>
<span id="cb43-28"><a href="#cb43-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb43-29"><a href="#cb43-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb43-30"><a href="#cb43-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb43-31"><a href="#cb43-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb43-32"><a href="#cb43-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb43-33"><a href="#cb43-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb43-34"><a href="#cb43-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-35"><a href="#cb43-35" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(tainan_dengue_cases_by_village_map, tainan_towns_map)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The choropleth map on the left is used to visualize this distribution. The total number of dengue cases reported is by village level and it can range from 0 to 357. This means that there are villages that are totally clear from dengue cases.</p>
<p>Another interesting insight we discover is that villages that are situated nearer to the center tend to have higher number of dengue cases reported.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>equal <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(tainan_dengue_cases_by_village) <span class="sc">+</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"total_dengue_cases"</span>,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">n =</span> <span class="dv">5</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"equal"</span>) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal interval classification"</span>)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>quantile <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(tainan_dengue_cases_by_village) <span class="sc">+</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"total_dengue_cases"</span>,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">n =</span> <span class="dv">5</span>,</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal quantile classification"</span>)</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(equal, </span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>             quantile, </span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">asp=</span><span class="dv">1</span>, </span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="spatial-autocorrelation-analysis" class="level1">
<h1>6.0 Spatial Autocorrelation Analysis</h1>
<blockquote class="blockquote">
<p>“Everything is related to everything else, but near things are more related than distant things.”</p>
<p>– Waldo Tobler, The First Law of Geography</p>
</blockquote>
<p><strong>Spatial Autocorrelation</strong> is used to describe the presence of systematic spatial variation or correlation in a variable.</p>
<p>The two main types of Spatial Autocorrelation Analysis are:</p>
<ul>
<li><p>Global spatial autocorrelation analysis</p></li>
<li><p>Local spatial autocorrelation analysis</p></li>
</ul>
<section id="global-spatial-autocorrelation-analysis" class="level3">
<h3 class="anchored" data-anchor-id="global-spatial-autocorrelation-analysis">6.2.1 Global Spatial Autocorrelation Analysis</h3>
<section id="gloabl-measures-of-spatial-autocorrelation-morans-i-and-gearys-c" class="level4">
<h4 class="anchored" data-anchor-id="gloabl-measures-of-spatial-autocorrelation-morans-i-and-gearys-c">6.2.1.1 Gloabl Measures of Spatial Autocorrelation: Moran’s I and Geary’s C</h4>
<p>We can assess spatial autocorrelation using the Moran’s I or Geary’s C.</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 49%">
</colgroup>
<thead>
<tr class="header">
<th>Moran’s I</th>
<th>Geary’s C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><img src="imgs/global_moran_i.png" class="img-fluid"></td>
<td><img src="imgs/global_geary_c.png" class="img-fluid"></td>
</tr>
<tr class="even">
<td><p>Describe how features differ from the values in the study area as a whole.</p>
<p>The value of Moran’s I can range from -1 to 1:</p>
<ul>
<li><p>positive (I&gt;0): Clustered, observations tend to be similar;</p></li>
<li><p>negative(I&lt;0): Dispersed, observations tend to be dissimilar;</p></li>
<li><p>approximately zero: observations are arranged randomly over space.</p></li>
</ul></td>
<td><p>Describing how features differ from their immediate neighbours.</p>
<p>The value of Geary’s&nbsp;<em>C</em> can range from 0 to &gt;1:</p>
<ul>
<li><p>Large c value (&gt;1) : Dispersed, observations tend to be dissimilar;</p></li>
<li><p>Small c value (&lt;1) : Clustered, observations tend to be similar;</p></li>
<li><p>c = 1: observations are arranged randomly over space.</p></li>
</ul></td>
</tr>
</tbody>
</table>
<p>In this Take-home Exercise, we use Moran’s I to test the spatial autocorrelation. To test for spatial autocorrelation, we can follow the steps below:</p>
<ol type="1">
<li>State the null and alternative hypotheses
<ul>
<li>H<sub>0</sub> (null hypothesis): The distribution of dengue fever outbreak at Tainan City are independent from space and time (i.e.&nbsp;spatial indepndent, randomly dispersed)</li>
<li>H<sub>1</sub> (alternative hypothesis): The distribution of dengue fever outbreak at Tainan City are not independent from space and time (i.e.&nbsp;spatial dependent)</li>
</ul></li>
<li>Choose the significance level ⍺
<ul>
<li>Statistically, we select the confident interval as 95% =&gt; alpha value (⍺) = 0.05.</li>
</ul></li>
<li>Derive the Moran’s I, z-score and p-value</li>
<li>State the conclusion
<ul>
<li>Reject the Null hypothesis (H<sub>0</sub>) if p-value &lt; alpha value (⍺) = 0.05</li>
<li>Failed to reject the Null Hypothesis (H<sub>0</sub>) if p-value &gt; alpha value (⍺) = 0.05</li>
</ul></li>
</ol>
</section>
<section id="computing-spatial-weights" class="level4">
<h4 class="anchored" data-anchor-id="computing-spatial-weights">6.2.1.2 Computing Spatial Weights</h4>
<p>To calculate global spatial autocorrelation statistics effectively, we need to first construct the spatial weights for the study area. The spatial weights play a critical role in defining the neighbourhood relationships between geographical units within the study area.</p>
<p>There are several methods to construct spatial weights. We will be using the Contiguity-Based method to construct the spatial weights and derive the Weights Matrix.</p>
<p><strong>Contiguity-Based Weights</strong></p>
<p>This method establishes neighbourhood relationships based on contiguity, where geographical units sharing common borders (boundaries) are considered neighbours. Contiguity can be further categorised into the following cases:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="imgs/contiguity-based_criterions.png" class="img-fluid figure-img"></p>
</figure>
</div>
<ul>
<li><p>“rook” criterion (sharing a common edge)</p></li>
<li><p>“bishop” criterion (sharing common vertices)</p></li>
<li><p>“queen” criterion (sharing a common edge or vertex)</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>“rook” and “queen” criterions are more commonly used.</p>
</div>
</div>
<p>To derive the <strong>Contiguity-Based Weights,</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> tainan_dengue_cases_by_village <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry),</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">wt =</span> <span class="fu">st_weights</span>(nb,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">style =</span> <span class="st">"W"</span>),</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 258
Columns: 9
$ nb                 &lt;nb&gt; &lt;6, 118, 160&gt;, &lt;126, 128, 138, 168, 222&gt;, &lt;68, 69, 1…
$ wt                 &lt;list&gt; &lt;0.3333333, 0.3333333, 0.3333333&gt;, &lt;0.2, 0.2, 0.2,…
$ COUNTYNAME         &lt;chr&gt; "臺南市", "臺南市", "臺南市", "臺南市", "臺南市", "…
$ TOWNID             &lt;chr&gt; "D06", "D32", "D08", "D02", "D06", "D06", "D08", "D…
$ TOWNNAME           &lt;chr&gt; "安南區", "仁德區", "中西區", "南區", "安南區", "安…
$ VILLNAME           &lt;chr&gt; "青草里", "保安里", "赤嵌里", "大成里", "城北里", "…
$ TOWNNAME_VILLNAME  &lt;chr&gt; "安南區_青草里", "仁德區_保安里", "中西區_赤嵌里", …
$ total_dengue_cases &lt;int&gt; 2, 19, 111, 29, 1, 10, 37, 48, 108, 66, 26, 2, 3, 1…
$ geometry           &lt;POLYGON [°]&gt; POLYGON ((120.1176 23.08387..., POLYGON ((1…</code></pre>
</div>
</div>
</section>
<section id="perform-global-morans-i-test" class="level4">
<h4 class="anchored" data-anchor-id="perform-global-morans-i-test">6.2.1.3 Perform Global Moran’s I Test</h4>
<p>After formulating the null and alternative hypotheses, we can perform the Global Moran’s I Test to derive the Moran’s I, z-score and p-value using the global_moran_test() function from sfdep package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">global_moran_test</span>(wm_q<span class="sc">$</span>total_dengue_cases,</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>nb,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>wt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  x  
weights: listw    

Moran I statistic standard deviate = 11.538, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.419567083      -0.003891051       0.001347083 </code></pre>
</div>
</div>
<p><strong>Interpreting the results</strong></p>
<ul>
<li><p>The Moran I statistic standard deviate is 11.538.</p></li>
<li><p>The Moran’s I statistic is 0.420. This indicates positive spatial correlation (signs of clusterings)</p></li>
<li><p>The p-value is extremely small (&lt; 2.2e-16).</p></li>
</ul>
<p>We observe the p-value obtained is lower than the significance level (⍺) of 0.05. Thus, we have enough evidence to reject the null hypothesis and conclude the distribution of dengue fever outbreak at Tainan City are not independent from space and time, but spatially dependent. This spatial dependency implies that the likelihood of a dengue fever outbreak in one village is not occurred by random chance but is influenced by neighboring villages.</p>
</section>
<section id="perform-global-morans-i-permutation-test-with-monte-carlo-simulation" class="level4">
<h4 class="anchored" data-anchor-id="perform-global-morans-i-permutation-test-with-monte-carlo-simulation">6.2.1.4 Perform Global Moran’s I Permutation Test with Monte-Carlo Simulation</h4>
<p>In practice, the Monte-Carlo Simulation should be used to perform the statistical test. We can use the global_moran_perm() function of sfdep package to run the Monte-Carlo Simulation.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The set.seed() function in R is used to create reproducible results when writing code that involves creating variables that take on random values. The value placed in the seed can be any random integer. By using the set.seed() function, you guarantee that the same random values are produced each time you run the code. Read more about setting seeds <a href="https://www.statology.org/set-seed-in-r/">here</a>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>global_moranI_perm <span class="ot">&lt;-</span> <span class="fu">global_moran_perm</span>(wm_q<span class="sc">$</span>total_dengue_cases,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>nb,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>wt,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">nsim =</span> <span class="dv">999</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>global_moranI_perm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  x 
weights: listw  
number of simulations + 1: 1000 

statistic = 0.41957, observed rank = 1000, p-value &lt; 2.2e-16
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The number of simulations is always equal to nsim + 1. Since nsim = 999, this means that we will be performing 1000 simulations.</p>
</div>
</div>
<p><strong>Interpreting the results</strong></p>
<ul>
<li><p>The Moran’s I statistic is 0.420. This indicates positive spatial correlation (signs of clusterings)</p></li>
<li><p>The p-value is extremely small (&lt; 2.2e-16).</p></li>
</ul>
<p>The results from the Monte-Carlo Simulation aligns with the Global Moran’s I Test conducted earlier on. The p-value obtained is lower than the significance level (⍺) of 0.05. This means that we enough evidence to reject the null hypothesis and conclude the distribution of dengue fever outbreak at Tainan City are not independent from space and time, but spatially dependent.</p>
</section>
<section id="visualising-global-monte-carlo-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="visualising-global-monte-carlo-morans-i">6.2.1.5 Visualising Global Monte-Carlo Moran’s I</h4>
<p>Let us visualise the simulated Moran’s I test statistics by plotting the distribution of the statistical values using a histogram.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(global_moranI_perm<span class="sc">$</span>res, </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq=</span><span class="cn">TRUE</span>, </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">20</span>, </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Simulated Moran's I"</span>)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>, </span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"red"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can also look at the summary statistics using the summary() function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(global_moranI_perm<span class="sc">$</span>res[<span class="dv">1</span><span class="sc">:</span><span class="dv">999</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-0.096859 -0.029067 -0.005498 -0.003422  0.021568  0.118326 </code></pre>
</div>
</div>
</section>
</section>
<section id="local-spatial-autocorrelation-analysis" class="level3">
<h3 class="anchored" data-anchor-id="local-spatial-autocorrelation-analysis">6.2.2 Local Spatial Autocorrelation Analysis</h3>
<p>Even though the Global Spatial Autocorrelation analysis can confirm the presence of clusters or a positive spatial relationship between number of dengue cases and their respective villages, it does not pinpoint the specific locations of these clusters. This is where Local Spatial Autocorrelation analysis becomes essentially useful.</p>
<section id="computing-local-morans-i-and-p-value" class="level4">
<h4 class="anchored" data-anchor-id="computing-local-morans-i-and-p-value">6.2.2.1 Computing Local Moran’s I and p-value</h4>
<p>To conduct the Local Spatial Autocorrelation analysis, we will need to compute the Local Moran’s I using the local_moran() function. The output <code>lisa</code> will be saved as a sf data.frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>lisa <span class="ot">&lt;-</span> wm_q <span class="sc">%&gt;%</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">local_moran =</span> <span class="fu">local_moran</span>(</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>    total_dengue_cases, nb, wt, <span class="at">nsim =</span> <span class="dv">999</span>),</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(local_moran)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(lisa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 20 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 120.0936 ymin: 22.9156 xmax: 120.2585 ymax: 23.08827
Geodetic CRS:  TWD97
# A tibble: 6 × 21
        ii      eii var_ii    z_ii    p_ii p_ii_sim p_folded_sim skewness
     &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt;
1  0.968   -0.0188  0.361   1.64   0.101      0.032        0.016   -0.785
2  0.476    0.00313 0.113   1.41   0.160      0.09         0.045   -0.810
3 -0.485   -0.00141 0.0807 -1.70   0.0886     0.06         0.03     0.591
4  0.00611 -0.00830 0.0546  0.0617 0.951      0.95         0.475   -0.576
5  1.01     0.00667 0.256   1.98   0.0477     0.004        0.002   -0.753
6  0.896   -0.0165  0.108   2.77   0.00553    0.002        0.001   -0.539
# ℹ 13 more variables: kurtosis &lt;dbl&gt;, mean &lt;fct&gt;, median &lt;fct&gt;, pysal &lt;fct&gt;,
#   nb &lt;nb&gt;, wt &lt;list&gt;, COUNTYNAME &lt;chr&gt;, TOWNID &lt;chr&gt;, TOWNNAME &lt;chr&gt;,
#   VILLNAME &lt;chr&gt;, TOWNNAME_VILLNAME &lt;chr&gt;, total_dengue_cases &lt;int&gt;,
#   geometry &lt;POLYGON [°]&gt;</code></pre>
</div>
</div>
<p>Based on the documentation for <a href="https://r-spatial.github.io/spdep/reference/localmoran.html">sfdep</a>, the output will be a will be <code>data.frame</code> containing the following columns:</p>
<ul>
<li><p><code>ii</code>: local moran statistics</p></li>
<li><p><code>eii</code>: expectation of local moran statistics</p></li>
<li><p><code>var_ii</code>: variance of local moran statistics</p></li>
<li><p><code>z_ii</code>: standard deviate of local moran statistics</p></li>
<li><p><code>p_ii</code>: p-value of local moran statistics</p></li>
<li><p><code>p_ii_sim</code>: For&nbsp;<code>localmoran_perm</code>,&nbsp;<a href="https://rdrr.io/r/base/rank.html"><code>rank()</code></a>&nbsp;and&nbsp;<a href="https://rdrr.io/r/stats/Uniform.html"><code>punif()</code></a>&nbsp;of observed statistic rank for [0, 1] p-values using&nbsp;<code>alternative=</code></p></li>
<li><p><code>p_folded_sim</code>: the simulation folded [0, 0.5] range ranked p-value</p></li>
</ul>
</section>
<section id="visualizing-local-morans-i-and-p-value" class="level4">
<h4 class="anchored" data-anchor-id="visualizing-local-morans-i-and-p-value">6.2.2.2 Visualizing local Moran’s I and p-value</h4>
<p>The tmap functions are used to prepare a choropleth map by using values in the <code>ii</code> (local moran statistics) and <code>p_ii_sim</code> fields.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"ii"</span>) <span class="sc">+</span> </span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Local Moran's I"</span>,</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.4</span>,</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"p_ii_sim"</span>,</span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="dv">1</span>),</span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a>              <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0.001"</span>, <span class="st">"0.01"</span>, <span class="st">"0.05"</span>, <span class="st">"Not sig"</span>)) <span class="sc">+</span> </span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb56-23"><a href="#cb56-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"p-value of Local Moran's I (with simulation)"</span>,</span>
<span id="cb56-24"><a href="#cb56-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb56-25"><a href="#cb56-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb56-26"><a href="#cb56-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb56-27"><a href="#cb56-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.4</span>,</span>
<span id="cb56-28"><a href="#cb56-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb56-29"><a href="#cb56-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb56-30"><a href="#cb56-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb56-31"><a href="#cb56-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb56-32"><a href="#cb56-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb56-33"><a href="#cb56-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb56-34"><a href="#cb56-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-35"><a href="#cb56-35" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(map1, map2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="visualize-the-local-indicator-of-spatial-association-lisa-map" class="level4">
<h4 class="anchored" data-anchor-id="visualize-the-local-indicator-of-spatial-association-lisa-map">6.2.2.3 Visualize the Local Indicator of Spatial Association (LISA) map</h4>
<p>The LISA map is a categorical map showing outliers and clusters. LISA map is an interpreted map by combining local Moran’s I of geographical areas and their respective p-values. There are two types of outliers namely: High-Low and Low-High outliers. Likewise, there are two types of clusters namely: High-High and Low-Low clusters.</p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 86%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Outliers</strong></td>
<td><ul>
<li><p><strong>High-Low (HL):</strong> the area having high number of dengue cases are surrounded by neighbors that have low number of dengue cases</p></li>
<li><p><strong>Low-High (LH):</strong> the area having low number of dengue cases are surrounded by neighbors that have high number of dengue cases</p></li>
</ul></td>
</tr>
<tr class="even">
<td><strong>Clusters</strong></td>
<td><ul>
<li><p><strong>High-High (HH):</strong> Areas having high number of dengue cases are surrounded by neighbors that also have high number of dengue cases</p></li>
<li><p><strong>Low-Low (LL):</strong> the area having low number of dengue cases are surrounded by neighbors that also have low number of dengue cases</p></li>
</ul></td>
</tr>
</tbody>
</table>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>lisa_sig <span class="ot">&lt;-</span> lisa  <span class="sc">%&gt;%</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p_ii <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>lisa_map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lisa_sig) <span class="sc">+</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"mean"</span>) <span class="sc">+</span> </span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"LISA Map"</span>,</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.85</span>,</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.4</span>,</span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(lisa_map, tainan_towns_map, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Interpreting the results</strong></p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 86%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Outliers</strong></td>
<td><ul>
<li><p><strong>High-Low (HL):</strong> Only 1 village in 中西區 is an outlier (indicated as yellow on LISA map)</p></li>
<li><p><strong>Low-High (LH):</strong> 4 villages are outliers. These villages are located in 北區, 永康區 and 南區 (indicated as purple on LISA map)</p></li>
</ul></td>
</tr>
<tr class="even">
<td><strong>Clusters</strong></td>
<td><ul>
<li><p><strong>High-High (HH):</strong> These villages are located in 安南區, 北區, 永康區, 東區 and 南區 (indicated as red on LISA map)</p></li>
<li><p><strong>Low-Low (LL):</strong> These villages are located in 安南區, 安平區, 永康區 and 中西區 (indicated as green on LISA map)</p></li>
</ul></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="hot-spot-and-cold-spot-area-analysis-hcsa" class="level3">
<h3 class="anchored" data-anchor-id="hot-spot-and-cold-spot-area-analysis-hcsa">6.2.3 Hot Spot and Cold Spot Area Analysis (HCSA)</h3>
<p>HCSA uses spatial weights to identify locations of statistically significant hot spots and cold spots in an spatially weighted attribute that are in proximity to one another based on a calculated distance. The analysis groups features when similar high (hot) or low (cold) values are found in a cluster. The polygon features usually represent administration boundaries or a custom grid structure.</p>
<section id="derive-spatial-weights" class="level4">
<h4 class="anchored" data-anchor-id="derive-spatial-weights">6.2.3.1 Derive Spatial Weights</h4>
<p>As usual, we will need to derive a spatial weight matrix before we can compute local Gi* statistics. The spatial weight matrix will saved in <code>wm_idw</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>wm_idw <span class="ot">&lt;-</span> tainan_dengue_cases_by_village <span class="sc">%&gt;%</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry),</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">wts =</span> <span class="fu">st_inverse_distance</span>(nb, geometry,</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">scale =</span> <span class="dv">1</span>,</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">alpha =</span> <span class="dv">1</span>),</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="compute-gi-statistics" class="level4">
<h4 class="anchored" data-anchor-id="compute-gi-statistics">6.2.3.2 Compute Gi* statistics</h4>
<p>Next, let us compute the Gi* statistics with permutation. nsim is set to 999. This means that we will run 1000 simulations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>HCSA <span class="ot">&lt;-</span> wm_idw <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">local_Gi =</span> <span class="fu">local_gstar_perm</span>(</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>    total_dengue_cases, nb, wt, <span class="at">nsim =</span> <span class="dv">999</span>),</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(local_Gi)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>HCSA</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 258 features and 16 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 120.0627 ymin: 22.89401 xmax: 120.2925 ymax: 23.09144
Geodetic CRS:  TWD97
# A tibble: 258 × 17
   gi_star    e_gi   var_gi p_value   p_sim p_folded_sim skewness kurtosis nb   
     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;nb&gt; 
 1 -1.95   0.00291  2.65e-6 -1.61   0.107          0.03     0.015    0.885 &lt;int&gt;
 2 -1.64   0.00342  1.83e-6 -1.47   0.142          0.104    0.052    0.512 &lt;int&gt;
 3 -1.44   0.00419  1.30e-6 -1.81   0.0708         0.046    0.023    0.473 &lt;int&gt;
 4 -0.243  0.00360  1.88e-6 -0.0431 0.966          0.958    0.479    0.568 &lt;int&gt;
 5 -2.23   0.00303  2.15e-6 -1.92   0.0548         0.008    0.004    0.675 &lt;int&gt;
 6 -2.86   0.00348  1.47e-6 -2.72   0.00653        0.002    0.001    0.634 &lt;int&gt;
 7 -0.851  0.00350  1.97e-6 -0.729  0.466          0.51     0.254    0.839 &lt;int&gt;
 8  0.0858 0.00379  1.17e-6  0.165  0.869          0.8      0.4      0.449 &lt;int&gt;
 9  1.85   0.00432  1.94e-6  1.66   0.0964         0.134    0.067    0.637 &lt;int&gt;
10 -0.971  0.00394  1.81e-6 -1.05   0.296          0.284    0.142    0.538 &lt;int&gt;
# ℹ 248 more rows
# ℹ 8 more variables: wts &lt;list&gt;, COUNTYNAME &lt;chr&gt;, TOWNID &lt;chr&gt;,
#   TOWNNAME &lt;chr&gt;, VILLNAME &lt;chr&gt;, TOWNNAME_VILLNAME &lt;chr&gt;,
#   total_dengue_cases &lt;int&gt;, geometry &lt;POLYGON [°]&gt;</code></pre>
</div>
</div>
</section>
<section id="mapping-gi-statistics" class="level4">
<h4 class="anchored" data-anchor-id="mapping-gi-statistics">6.2.3.3 Mapping Gi* statistics</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"gi_star"</span>) <span class="sc">+</span> </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Gi* of Dengue cases"</span>,</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.85</span>,</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.4</span>,</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"p_value"</span>,</span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="dv">1</span>),</span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>              <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0.001"</span>, <span class="st">"0.01"</span>, <span class="st">"0.05"</span>, <span class="st">"Not sig"</span>)) <span class="sc">+</span> </span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"p-value of Gi*"</span>,</span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.85</span>,</span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.4</span>,</span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb61-30"><a href="#cb61-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb61-31"><a href="#cb61-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb61-32"><a href="#cb61-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb61-33"><a href="#cb61-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb61-34"><a href="#cb61-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-35"><a href="#cb61-35" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(map1, map2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now, we are ready to plot the significant (i.e.&nbsp;p-values &lt; 0.05) hot spot and cold spot areas by using appropriate tmap functions shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>HCSA_sig <span class="ot">&lt;-</span> HCSA  <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p_sim <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>tainan_towns_map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(tainan_towns_sf) <span class="sc">+</span> </span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"TOWNNAME"</span>) <span class="sc">+</span> </span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Map of Tainan Towns"</span>,</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.85</span>,</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.55</span>,</span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.4</span>,</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb62-17"><a href="#cb62-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb62-18"><a href="#cb62-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-19"><a href="#cb62-19" aria-hidden="true" tabindex="-1"></a>HCSA_sig_map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb62-20"><a href="#cb62-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb62-21"><a href="#cb62-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb62-22"><a href="#cb62-22" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(HCSA_sig) <span class="sc">+</span></span>
<span id="cb62-23"><a href="#cb62-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"gi_star"</span>) <span class="sc">+</span> </span>
<span id="cb62-24"><a href="#cb62-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb62-25"><a href="#cb62-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Map of significant hot spot and cold spot areas"</span>,</span>
<span id="cb62-26"><a href="#cb62-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb62-27"><a href="#cb62-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.85</span>,</span>
<span id="cb62-28"><a href="#cb62-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb62-29"><a href="#cb62-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.4</span>,</span>
<span id="cb62-30"><a href="#cb62-30" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.title.size =</span> <span class="fl">0.8</span>,</span>
<span id="cb62-31"><a href="#cb62-31" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb62-32"><a href="#cb62-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb62-33"><a href="#cb62-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb62-34"><a href="#cb62-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb62-35"><a href="#cb62-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)  </span>
<span id="cb62-36"><a href="#cb62-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-37"><a href="#cb62-37" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(tainan_dengue_cases_by_village_map, tainan_towns_map,</span>
<span id="cb62-38"><a href="#cb62-38" aria-hidden="true" tabindex="-1"></a>             lisa_map, HCSA_sig_map, <span class="at">widths =</span> <span class="fu">c</span>(.<span class="dv">5</span>, .<span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation of Getis-Ord Gi and Gi*
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>A hot spot area: significant and positive if location i is associated with relatively high values of the surrounding locations.</p></li>
<li><p>A cold spot area: significant and negative if location i is associated with relatively low values in surrounding locations.</p></li>
</ul>
</div>
</div>
<p><strong>Interpreting the results</strong></p>
<p>By comparing all the four maps above, we are able to come up with the following conclusions:</p>
<ul>
<li><p>Certain villages in 安南區 are cold spot areas while some are hot spot areas</p></li>
<li><p>However, majority of the villages in 安南區 are cold spot areas. These cold spot areas have relatively low number of dengue cases reported (ranging from 0 to 41 number of dengue cases)</p></li>
<li><p>The villages identified as hot spot areas in 安南區 and 永康區 have relatively high number of dengue cases reported (ranging from 211 to 357 number of dengue cases)</p></li>
<li><p>Certain villages in 東區 are identify as hot spot areas. These hot spot areas have relatively high number of dengue cases reported (ranging from 91 to 145)</p></li>
</ul>
<p>Let us find out the names of these villages that have high number of dengue cases reported</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>hotspot_areas <span class="ot">&lt;-</span> HCSA_sig <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(gi_star)) <span class="sc">%&gt;%</span> </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">3</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Villages with high number of dengue cases reported (TOWNNAME_VILLNAME): "</span>, hotspot_areas<span class="sc">$</span>TOWNNAME_VILLNAME)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Villages with high number of dengue cases reported (TOWNNAME_VILLNAME):  安南區_溪墘里 安南區_大安里 永康區_三合里</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="emerging-hot-spot-analysis-ehsa" class="level1">
<h1>7.0 Emerging Hot Spot Analysis (EHSA)</h1>
<p>Emerging Hot Spot Analysis (EHSA) is a spatio-temporal analysis method used for revealing and describing how hot spot and cold spot areas evolve over time. We will be using the spacetime cube that was created previously.</p>
<section id="derive-spatial-weights-1" class="level2">
<h2 class="anchored" data-anchor-id="derive-spatial-weights-1">7.1 Derive Spatial Weights</h2>
<p>Firstly, we need to derive the spatial weights.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>tainan_dengue_nb <span class="ot">&lt;-</span> tainan_dengue_st <span class="sc">%&gt;%</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(<span class="st">"geometry"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">include_self</span>(<span class="fu">st_contiguity</span>(geometry)),</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">wt =</span> <span class="fu">st_inverse_distance</span>(nb, geometry,</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">scale =</span> <span class="dv">1</span>,</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">alpha =</span> <span class="dv">1</span>),</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_nbs</span>(<span class="st">"nb"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_wts</span>(<span class="st">"wt"</span>)</span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tainan_dengue_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  TOWNNAME_VILLNAME EPIWEEK num_dengue_cases nb        wt       
  &lt;chr&gt;               &lt;dbl&gt;            &lt;int&gt; &lt;list&gt;    &lt;list&gt;   
1 安南區_青草里          31                0 &lt;int [4]&gt; &lt;dbl [4]&gt;
2 仁德區_保安里          31                1 &lt;int [5]&gt; &lt;dbl [5]&gt;
3 中西區_赤嵌里          31                0 &lt;int [4]&gt; &lt;dbl [4]&gt;
4 南區_大成里            31                0 &lt;int [5]&gt; &lt;dbl [5]&gt;
5 安南區_城北里          31                0 &lt;int [4]&gt; &lt;dbl [4]&gt;
6 安南區_城南里          31                0 &lt;int [6]&gt; &lt;dbl [6]&gt;</code></pre>
</div>
</div>
</section>
<section id="compute-gi-statistics-1" class="level2">
<h2 class="anchored" data-anchor-id="compute-gi-statistics-1">7.2 Compute Gi* statistics</h2>
<p>Next, we will compute the Gi* statistics using local_gstar_perm() function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>gi_stars <span class="ot">&lt;-</span> tainan_dengue_nb <span class="sc">%&gt;%</span> </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(EPIWEEK) <span class="sc">%&gt;%</span> </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gi_star =</span> <span class="fu">local_gstar_perm</span>(</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    num_dengue_cases, nb, wt)) <span class="sc">%&gt;%</span> </span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(gi_star)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mann-kendall-test" class="level2">
<h2 class="anchored" data-anchor-id="mann-kendall-test">7.3 Mann-Kendall Test</h2>
<p>The Mann-Kendall statistical test for trend is used to assess whether a set of data values is increasing over time or decreasing over time, and whether the trend in either direction is statistically significant. The null and alternative hypotheses we have are:</p>
<ul>
<li>H<sub>0</sub> (null hypothesis): There is no monotonic trend in the series</li>
<li>H<sub>1</sub> (alternative hypothesis): A trend exists (i.e.&nbsp;this trend can be positive, negative or non-null)</li>
</ul>
<p>Statistically, we select the confident interval as 95%. Therefore, the significance level (alpha value ⍺) = 0.05. We will be select 安南區_溪墘里 as our study area since it has reported the highest number of dengue cases.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>cbg <span class="ot">&lt;-</span> gi_stars <span class="sc">%&gt;%</span> </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TOWNNAME_VILLNAME <span class="sc">==</span> <span class="st">"安南區_溪墘里"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(TOWNNAME_VILLNAME, EPIWEEK, gi_star)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> cbg, </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> EPIWEEK, </span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> gi_star)) <span class="sc">+</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplotly</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-7a48b661bfceaeb183f8" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-7a48b661bfceaeb183f8">{"x":{"data":[{"x":[31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50],"y":[1.3872603098241103,4.1146729696406332,6.9818469294762284,10.175827716319793,8.1324908840466783,8.6330247480016009,6.8917797996192984,4.4476391409026546,1.2479889505036668,0.77295931560372122,1.0394881377113279,0.72833057010831836,0.9458580353994448,0.91837212046627936,0.64961289463943006,0.14467691836601637,-1.6380705855905255,1.6958682119339528,-0.49194373983803008,-0.47047518618429079],"text":["EPIWEEK: 31<br />gi_star:  1.3872603","EPIWEEK: 32<br />gi_star:  4.1146730","EPIWEEK: 33<br />gi_star:  6.9818469","EPIWEEK: 34<br />gi_star: 10.1758277","EPIWEEK: 35<br />gi_star:  8.1324909","EPIWEEK: 36<br />gi_star:  8.6330247","EPIWEEK: 37<br />gi_star:  6.8917798","EPIWEEK: 38<br />gi_star:  4.4476391","EPIWEEK: 39<br />gi_star:  1.2479890","EPIWEEK: 40<br />gi_star:  0.7729593","EPIWEEK: 41<br />gi_star:  1.0394881","EPIWEEK: 42<br />gi_star:  0.7283306","EPIWEEK: 43<br />gi_star:  0.9458580","EPIWEEK: 44<br />gi_star:  0.9183721","EPIWEEK: 45<br />gi_star:  0.6496129","EPIWEEK: 46<br />gi_star:  0.1446769","EPIWEEK: 47<br />gi_star: -1.6380706","EPIWEEK: 48<br />gi_star:  1.6958682","EPIWEEK: 49<br />gi_star: -0.4919437","EPIWEEK: 50<br />gi_star: -0.4704752"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(0,0,0,1)","dash":"solid"},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.228310502283104,"r":7.3059360730593621,"b":40.182648401826491,"l":48.949771689497723},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[30.050000000000001,50.950000000000003],"tickmode":"array","ticktext":["35","40","45","50"],"tickvals":[35,40,45,50],"categoryorder":"array","categoryarray":["35","40","45","50"],"nticks":null,"ticks":"outside","tickcolor":"rgba(179,179,179,1)","ticklen":3.6529680365296811,"tickwidth":0.33208800332088001,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(222,222,222,1)","gridwidth":0.33208800332088001,"zeroline":false,"anchor":"y","title":{"text":"EPIWEEK","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-2.2287655006860416,10.76652263141531],"tickmode":"array","ticktext":["0.0","2.5","5.0","7.5","10.0"],"tickvals":[0,2.4999999999999996,5,7.5,10],"categoryorder":"array","categoryarray":["0.0","2.5","5.0","7.5","10.0"],"nticks":null,"ticks":"outside","tickcolor":"rgba(179,179,179,1)","ticklen":3.6529680365296811,"tickwidth":0.33208800332088001,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(222,222,222,1)","gridwidth":0.33208800332088001,"zeroline":false,"anchor":"x","title":{"text":"gi_star","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(179,179,179,1)","width":0.66417600664176002,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"62c454a5686b":{"x":{},"y":{},"type":"scatter"}},"cur_data":"62c454a5686b","visdat":{"62c454a5686b":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p><strong>Interpreting the results</strong></p>
<p>By the looking at the graph of Gi* plotted against EPIWEEK, we observed a downward trend. This is statistically confirmed by the Mann-Kendall Test. Thus, we can reject the null hypothesis that there is no monotonic trend and infer that as time goes by, the spread of dengue cases in 安南區_溪墘里 gradually decreases in comparison to the other villages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>cbg <span class="sc">%&gt;%</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mk =</span> <span class="fu">list</span>(</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">unclass</span>(</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>      Kendall<span class="sc">::</span><span class="fu">MannKendall</span>(gi_star)))) <span class="sc">%&gt;%</span> </span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest_wider</span>(mk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
     tau       sl     S     D  varS
   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 -0.632 0.000113  -120  190.   950</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>ehsa <span class="ot">&lt;-</span> gi_stars <span class="sc">%&gt;%</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TOWNNAME_VILLNAME) <span class="sc">%&gt;%</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mk =</span> <span class="fu">list</span>(</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">unclass</span>(</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>      Kendall<span class="sc">::</span><span class="fu">MannKendall</span>(gi_star)))) <span class="sc">%&gt;%</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest_wider</span>(mk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>emerging <span class="ot">&lt;-</span> ehsa <span class="sc">%&gt;%</span> </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(sl, <span class="fu">abs</span>(tau)) <span class="sc">%&gt;%</span> </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="performing-emerging-hotspot-analysis" class="level2">
<h2 class="anchored" data-anchor-id="performing-emerging-hotspot-analysis">7.4 Performing Emerging Hotspot Analysis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>ehsa <span class="ot">&lt;-</span> <span class="fu">emerging_hotspot_analysis</span>(</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> tainan_dengue_st, </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">.var =</span> <span class="st">"num_dengue_cases"</span>, </span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">k =</span> <span class="dv">1</span>, </span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">nsim =</span> <span class="dv">99</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="visualising-the-distribution-of-ehsa-classes" class="level3">
<h3 class="anchored" data-anchor-id="visualising-the-distribution-of-ehsa-classes">7.4.1 Visualising the distribution of EHSA classes</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ehsa,</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> classification)) <span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Interpreting the results</strong></p>
<ul>
<li><p>More than 80 villages are classified as oscillating hotspots. This means that these villages are statistically significant hot spot for the final time-step interval that has a history of also being a statistically significant cold spot during a prior time step.</p></li>
<li><p>Less than 10 villages are classified as new hotspot. This means that these villages are statistically significant hot spot for the final time step and has never been a statistically significant hot spot before.</p></li>
</ul>
</section>
<section id="visualising-ehsa" class="level3">
<h3 class="anchored" data-anchor-id="visualising-ehsa">7.4.2 Visualising EHSA</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>tainan_ehsa <span class="ot">&lt;-</span> tainan_towns_sf <span class="sc">%&gt;%</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(ehsa,</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">join_by</span>(TOWNNAME_VILLNAME <span class="sc">==</span> location))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>ehsa_sig <span class="ot">&lt;-</span> tainan_ehsa  <span class="sc">%&gt;%</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p_value <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(tainan_ehsa) <span class="sc">+</span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(ehsa_sig) <span class="sc">+</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"classification"</span>) <span class="sc">+</span> </span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="references" class="level1">
<h1>8.0 References</h1>
<ul>
<li><p><a href="https://en.wikipedia.org/wiki/Geary%27s_C" class="uri">https://en.wikipedia.org/wiki/Geary%27s_C</a></p></li>
<li><p><a href="https://en.wikipedia.org/wiki/Moran%27s_I" class="uri">https://en.wikipedia.org/wiki/Moran%27s_I</a></p></li>
<li><p><a href="https://www.linkedin.com/pulse/exploratory-spatial-data-analysis-autocorrelation-thomas-dao-" class="uri">https://www.linkedin.com/pulse/exploratory-spatial-data-analysis-autocorrelation-thomas-dao-</a></p></li>
<li><p><a href="https://www.paulamoraga.com/book-spatial/spatial-autocorrelation.html" class="uri">https://www.paulamoraga.com/book-spatial/spatial-autocorrelation.html</a></p></li>
<li><p><a href="https://is415-ay2023-24t2.netlify.app/lesson/lesson05/lesson05-glsa" class="uri">https://is415-ay2023-24t2.netlify.app/lesson/lesson05/lesson05-glsa</a></p></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Handle positioning of the toggle
      window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>