---
title: "Take-home Exercise 1: Application of Spatial Point Patterns Analysis to discover the geographical distribution of Grab hailing services in Singapore"
execute:
  eval: true
  echo: true
  warning: false
date: 01/23/2024
date-modified: last-modified
---

# 1.0 Introduction

## 1.1. Overview - Setting the Scene

Human mobility, the movement of human beings in space and time, reflects the spatial-temporal characteristics of human behavior. With the advancement Information and Communication Technologies (ICT) especially smart phone, a large volume of data related to human mobility have been collected. By using appropriate GIS analysis methods, these data are potentially useful in supporting smart city planning and management.

In Singapore, one of the important source of data related to human mobility is from [Land Transport Authority (LTA) DataMall](https://datamall.lta.gov.sg/content/datamall/en.html). Two data sets related to human mobility are provided by the portal, they are: Passenger Volume by Origin Destination Train Stations and Passenger Volume by Origin Destination Bus Stops. One of the limitation of these data sets is that their location are biased to either bus stops or MRT/LRT stations. In 2020, another very interesting human mobility data set called [Grab Posisi](https://engineering.grab.com/grab-posisi) was released by GRAB, one of the largest shared taxi operator in South-east Asia. There are two data sets been released and one of them is for Singapore.

## 1.2 Objectives

Geospatial analytics hold tremendous potential to address complex problems facing society.

In this study, we will be working on the following tasks:

-   Apply appropriate spatial point patterns analysis methods

-   Discover the geographical and spatial-temporal distribution of Grab hailing services locations in Singapore

## 1.3 Getting Started

In this take-home exercise, we will be using the following packages:

-   arrow

-   [sf](https://cran.r-project.org/web/packages/sf/) for handling geospatial data

-   [tidyverse](https://www.tidyverse.org/packages/) for performing data science tasks such as importing, wrangling and visualising data

```{r}
pacman::p_load(arrow, lubridate, tidyverse, tmap, sf)
```

# 2.0 Data Acquisition

There will be 3 data sets used in this exercise:

| Data                                       | Format    | Description                                                 | Source                                                      |
|-------------|-------------|-----------------------------------|-------------|
| Grab Posisi                                | Parquet   | Grab taxi location points either by origins or destinations | [Grab](https://engineering.grab.com/grab-posisi)            |
| Road                                       | Shapefile | Road layer within Singapore excluding outer islands         | [Geofabrik download server](https://download.geofabrik.de/) |
| Master Plan 2019 Subzone Boundary (No Sea) | GeoJSON   | Singapore boundary layer excluding outer islands            | [Data.gov.sg](https://beta.data.gov.sg/)                    |

## 2.1 Extracting Geospatial and Aspatial Data Sets

Start by creating a new folder labeled `Take-home_Ex01`. Within this folder, create a sub-folder named `data`. Inside the `data` sub-folder, create two additional sub-folders and rename them `geospatial` and `aspatial` respectively.

Unzip the `malaysia-singapore-brunei-latest-free.shp.zip` folder and place all files, `MasterPlan2019SubzoneBoundaryNoSeaGEOJSON.geojson` into `geospatial` sub-folder.

Place all files from `GrabPosisi` into `aspatial` sub-folder.

::: callout-tip
## Tip

Did you observe that the file names from `GrabPosisi` and `MasterPlan2019SubzoneBoundaryNoSeaGEOJSON.geojson` are quite lengthy? Shortening them could make processing more convenient later on.
:::

# 3.0 Geospatial Data Wrangling

## 3.1 Importing Geospatial Data

In the previous exercise, we have learnt to import geospatial data into RStudio by using *st_read()* of **sf** package. Let’s try it now!
